# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecb299bc587cd8c96bc772dccf71da95f011c03063a6e4756ac10d4710f5d63389cd357e1f07704ac0610e5c14f827aeaece529d53270fb4961d7746d9cf849

test:
  secret_key_base: 081b553f054d1ac4f20342851357269d798e522b4c384430e69aa4af6d515fa49e6360cb91149531c9dfcc65eecfaf100af65e72c9a6791903d7dc27a4224faf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
